### ISSUE TITLE
Chunk size bug nello script di training

### ISSUE THREAD

**Issue by dondavide04** [collab-uniba/pySenti4SD#1]
L'esecuzione dello script di training termina con errore se si seleziona un chunk size sottomultiplo del numero di esempi del file .csv di training.

Di seguito un esempio di 3 esecuzioni di test usando un dataset .csv di 100 righe (101 considerando la prima riga con le intestazioni), con chunk size rispettivamente di 10,20,50:
![10](https://user-images.githubusercontent.com/37539937/69356380-aebb9700-0c83-11ea-88aa-9bc6ef612179.png)
![20](https://user-images.githubusercontent.com/37539937/69356431-bed37680-0c83-11ea-9ce3-a1e2d3996e91.png)
![50](https://user-images.githubusercontent.com/37539937/69356446-c266fd80-0c83-11ea-9b69-66e5e2f91185.png)
Modificando il chunk size con un numero non sottomultiplo (testato con 30 e 70) l'esecuzione termina senza problemi.

L'errore è stato scoperto casualmente lanciando lo script su un training set di 4000 esempi con il chunk size di default uguale a 1000.

**Comment by bateman** [comment]
@dondavide04 , please send the PR that closes this issue
